---
title: "Performing a spatial analysis of multiplexed tissue imaging data."
author: "Alexander Nicholls and Ellis Patrick"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


```{r}
library(cytomapper)
library(dplyr)
```

# Read in images

Our images are stored in the `images` folder within the `Data` folder. We can use `loadImages()` from the `cytomapper` package to load all of the tiff images in this folder into a `CytoImageList` object.


```{r}

pathToImages <- "Data/images"

# Get directories of images
imageDirs <- dir(pathToImages, full.names = TRUE)
names(imageDirs) <- dir(pathToImages, full.names = FALSE)

# Get files in each directory
files <- sapply(imageDirs, list.files, pattern = "tif", full.names = TRUE, simplify = FALSE)

# Read files with readImage from EBImage
images <- lapply(files, readImage, as.is = TRUE)


```


```{r}

# Store images in a CytoImageList with images on_disk as h5 files to save memory. 
dir.create("Data/h5Files")
images <- CytoImageList(images, on_disk = TRUE, h5FilesPath = "Data/h5Files")

mcols(images) <- S4Vectors::DataFrame(ImageNb = names(images))

gc()
```


# Load the clinical data

```{r}

clinical <- read.csv("Data/1-s2.0-S0092867421014860-mmc1.csv")
clinical <- clinical |>
  mutate(imageID = paste0("Point", PointNumber, "_pt", Patient_ID, "_", TMAD_Patient))

clinicalVariables <- c("imageID", "Patient_ID","Status", "Age", "SUBTYPE", "PAM50", "Treatment", "DCIS_grade", "Necrosis")

rownames(clinical) <- clinical$imageID

clinical <- clinical[names(images), ]

```


# Segment the images

```{r}

img <- images[1]
img[[1]] <- sqrt(img[[1]])

masks <- simpleSeg(images,
                   nucleus = "HH3",
                   cellBody = "dilate",
                   sizeSelection = 10,
                   discSize = 3,
                   cores = 5,
                   tolerance = 1)

mcols(masks) <- S4Vectors::DataFrame(ImageNb = names(masks)[1])

display(colorLabels(masks[[1]]))

```


# Check segmentation

```{r}
plotPixels(images[1], mask = masks[1], img_id = "ImageNb", colour_by = c("HH3", "CD45"))
```

